services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: monitor
      POSTGRES_PASSWORD: monitorpass
      POSTGRES_DB: monitor_db
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build: ./backend
    environment:
      DATABASE_URL: postgresql+psycopg://monitor:monitorpass@db:5432/monitor_db
      JWT_SECRET: change_me_in_production
      PYTHONPATH: /app

      # EMAIL SETTINGS (ADD THESE)
      SMTP_HOST: smtp.gmail.com
      SMTP_PORT: 587
      SMTP_USER: itsmechhetri007@gmail.com
      SMTP_PASSWORD: yxin suop oubk dmkh
      SMTP_FROM: itsmechhetri007@gmail.com
      ALERT_EMAIL_TO: chhetrimandeepp@gmail.com

    ports:
      - "8000:8000"
    volumes:
      - ./frontend/static:/frontend/static:ro
    depends_on:
      - db

volumes:
  dbdata: